{"testsuite": {"@errors": "1", "@failures": "1", "@file": ".py", "@name": "TestSequenceFunctions-20200727210600", "@skipped": "2", "@tests": "10", "@time": "0.009", "@timestamp": "2020-07-27T21:06:00", "testcase": [{"@classname": "TestSequenceFunctions", "@file": "main.py", "@line": "65", "@name": "test_choice", "@time": "0.006", "@timestamp": "2020-07-27T21:06:00", "system-out": null, "system-err": null}, {"@classname": "TestSequenceFunctions", "@file": "main.py", "@line": "29", "@name": "test_isupper", "@time": "0.000", "@timestamp": "2020-07-27T21:06:00", "system-out": null, "system-err": null}, {"@classname": "TestSequenceFunctions", "@file": "main.py", "@line": "69", "@name": "test_sample", "@time": "0.001", "@timestamp": "2020-07-27T21:06:00", "system-out": null, "system-err": null}, {"@classname": "TestSequenceFunctions", "@file": "main.py", "@line": "56", "@name": "test_shuffle", "@time": "0.000", "@timestamp": "2020-07-27T21:06:00", "system-out": null, "system-err": null}, {"@classname": "TestSequenceFunctions", "@file": "main.py", "@line": "33", "@name": "test_split", "@time": "0.000", "@timestamp": "2020-07-27T21:06:00", "system-out": null, "system-err": null}, {"@classname": "TestSequenceFunctions", "@file": "main.py", "@line": "26", "@name": "test_upper", "@time": "0.000", "@timestamp": "2020-07-27T21:06:00", "system-out": null, "system-err": null}, {"@classname": "TestSequenceFunctions", "@file": "main.py", "@line": "44", "@name": "test_fail", "@time": "0.000", "@timestamp": "2020-07-27T21:06:00", "failure": {"@message": "1 != 2", "@type": "AssertionError", "#text": "Traceback (most recent call last):\n  File \"main.py\", line 46, in test_fail\n    self.assertEqual(1, 2)\nAssertionError: 1 != 2"}, "system-out": null, "system-err": null}, {"@classname": "TestSequenceFunctions", "@file": "main.py", "@line": "40", "@name": "test_error", "@time": "0.001", "@timestamp": "2020-07-27T21:06:00", "error": {"@message": "", "@type": "ValueError", "#text": "Traceback (most recent call last):\n  File \"main.py\", line 42, in test_error\n    raise ValueError\nValueError"}, "system-out": null, "system-err": null}, {"@classname": "TestSequenceFunctions", "@file": "main.py", "@line": "48", "@name": "test_skip", "@time": "0.000", "@timestamp": "2020-07-27T21:06:00", "skipped": {"@message": "This is a skipped test.", "@type": "skip"}, "system-out": null, "system-err": null}, {"@classname": "TestSequenceFunctions", "@file": "main.py", "@line": "52", "@name": "test_skipped", "@time": "0.000", "@timestamp": "2020-07-27T21:06:00", "skipped": {"@message": "demonstrating skipping", "@type": "skip"}, "system-out": null, "system-err": null}]}}